export const MUSIC_FETCH_START = "MUSIC_FETCH_START";
export const MUSIC_FETCH_LOADING = "MUSIC_FETCH_LOADING";
export const MUSIC_FETCH_SUCCESS = "MUSIC_FETCH_SUCCESS"; 
export const MUSIC_FETCH_ERROR = "MUSIC_FETCH_ERROR"; 
export const DOWNLOAD_MUSIC = "DOWNLOAD_MUSIC"; 
